
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091 :8090"  # Exposes 8090 internally but uses 8091 on the host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - myapp_network2

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"  # Exposes 5432 internally but uses 5433 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp_network2

volumes:
  postgres_data:

networks:
  myapp_network2:
    driver: bridge
